In [7]:
import pandas as pd
data = pd.DataFrame({
    'Region': ['North', 'North', 'South', 'South', 'East', 'East'],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 200, 150, 50, 300, 100],
    'Quantity': [10, 20, 15, 5, 30, 10]
})

In [8]:
revenue = data['Sales']* data['Quantity']

In [10]:
max(revenue)

9000

In [11]:
employees = pd.DataFrame({
    'EmpID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'DeptID': [101, 102, 101, 102],
    'Salary': [60000, 50000, 70000, 55000]
})
departments = pd.DataFrame({
    'DeptID': [101, 102],
    'DeptName': ['HR', 'IT']
})

In [26]:
a=employees.rank()

In [31]:
a

   EmpID  Name  DeptID  Salary
0    1.0   1.0     1.5     3.0
1    2.0   2.0     3.5     1.0
2    3.0   3.0     1.5     4.0
3    4.0   4.0     3.5     2.0

In [32]:

b=departments.rank()

In [30]:
b

   DeptID  DeptName
0     1.0       1.0
1     2.0       2.0

In [29]:
pd.concat([a,b])

   EmpID  Name  DeptID  Salary  DeptName
0    1.0   1.0     1.5     3.0       NaN
1    2.0   2.0     3.5     1.0       NaN
2    3.0   3.0     1.5     4.0       NaN
3    4.0   4.0     3.5     2.0       NaN
0    NaN   NaN     1.0     NaN       1.0
1    NaN   NaN     2.0     NaN       2.0

In [34]:
txt = "John_Larter"

x = txt.split("_")

print(x)

['John', 'Larter']

In [41]:
import pandas as pd

data = {
    'Name': ['John_Larter', 'Robert_Junior', 'Jonny_Depp'],
    'email': ['Jonny@gmail.com', 'Robert@gmail.com', 'Jonny@gmail.com'],
    'address': ['abc', 'hhyd', 'kkk'],
    'mobile number': [000000, 000000, 0000000]
}

df = pd.DataFrame(data)
print(df)

            Name             email address  mobile number
0    John_Larter   Jonny@gmail.com     abc              0
1  Robert_Junior  Robert@gmail.com    hhyd              0
2     Jonny_Depp   Jonny@gmail.com     kkk              0

In [42]:
df = pd.DataFrame(data)
df[['firstname', 'lastname']] = df['Name'].apply(lambda x: pd.Series(x.split('_')))
df = df[['Name', 'email', 'address', 'mobile number' , 'firstname', 'lastname',]]
print(df)

            Name             email address  mobile number firstname lastname
0    John_Larter   Jonny@gmail.com     abc              0      John   Larter
1  Robert_Junior  Robert@gmail.com    hhyd              0    Robert   Junior
2     Jonny_Depp   Jonny@gmail.com     kkk              0     Jonny     Depp

In [43]:

interns = list(range(1, 101))

print(interns[:10])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:

matrix = [list(range(i, i + 10)) for i in range(1, 101, 10)]
matrix

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
 [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
 [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
 [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
 [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
 [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
 [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
 [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]

In [53]:

df=matrix = [list(range(i, i + 9)) for i in range(2, 101, 10)]
matrix

[[2, 3, 4, 5, 6, 7, 8, 9, 10],
 [12, 13, 14, 15, 16, 17, 18, 19, 20],
 [22, 23, 24, 25, 26, 27, 28, 29, 30],
 [32, 33, 34, 35, 36, 37, 38, 39, 40],
 [42, 43, 44, 45, 46, 47, 48, 49, 50],
 [52, 53, 54, 55, 56, 57, 58, 59, 60],
 [62, 63, 64, 65, 66, 67, 68, 69, 70],
 [72, 73, 74, 75, 76, 77, 78, 79, 80],
 [82, 83, 84, 85, 86, 87, 88, 89, 90],
 [92, 93, 94, 95, 96, 97, 98, 99, 100]]

In [56]:
import pandas as pd
import string

df = pd.DataFrame({'numbers': [12, 13, 14, 15, 16, 17, 18, 19, 20]})

alphabet = string.ascii_lowercase

df['letters'] = df['numbers'].apply(lambda x: alphabet[x-1])

In [57]:
df

   numbers letters
0       12       l
1       13       m
2       14       n
3       15       o
4       16       p
5       17       q
6       18       r
7       19       s
8       20       t

In [64]:

filtered_df = df[~df['letters'].str.contains('e', na=False)]
filtered_df

   numbers letters
0       12       l
1       13       m
2       14       n
3       15       o
4       16       p
5       17       q
6       18       r
7       19       s
8       20       t

In [67]:

result = df.groupby('letters')['letters'].sum()
result

letters
l    l
m    m
n    n
o    o
p    p
q    q
r    r
s    s
t    t
Name: letters, dtype: object

In [ ]:
# Goutham question 
import pandas as pd
data = {'customer_id': [1, 1, 2, 3],
        'amount': [100, 200, 50, 500]}
df = pd.DataFrame(data)
customer_spend = df.groupby('customer_id')['amount'].sum().reset_index()
def segment_customer(total_spend):
    if total_spend > 300:
        return 'High Value'
    elif 100 <= total_spend <= 300:
        return 'Medium'
    else:
        return 'Low'
customer_spend['Segment'] = customer_spend['amount'].apply(segment_customer)
print(customer_spend)

   customer_id  amount     Segment
0            1     300      Medium
1            2      50         Low
2            3     500  High Value

In [ ]:
#Kowshik question
import pandas as pd

l1 = list(range(1, 101))
l2 = [l1[i:i+10] for i in range(0, 100, 10)]

l3 = [list(range(i, i + 10, 2)) for i in range(2, 101, 10)]

df = pd.DataFrame(l2)
df.iloc[:, 0] = ['A', 'A', 'B', 'C', 'D', 'E', 'E', 'E', 'F', 'F']
df_filtered = df[df.iloc[:, 0] < 'E']
grouped_sum = df.groupby(df.columns[0])[df.columns[3]].sum()
print("1:", l1)
print("2:", l2)
print("3:", l3)
print("4:\n", df)
print("5:\n", df_filtered)
print("6:\n", grouped_sum)

1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
2: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40], [41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [51, 52, 53, 54, 55, 56, 57, 58, 59, 60], [61, 62, 63, 64, 65, 66, 67, 68, 69, 70], [71, 72, 73, 74, 75, 76, 77, 78, 79, 80], [81, 82, 83, 84, 85, 86, 87, 88, 89, 90], [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
3: [[2, 4, 6, 8, 10], [12, 14, 16, 18, 20], [22, 24, 26, 28, 30], [32, 34, 36, 38, 40], [42, 44, 46, 48, 50], [52, 54, 56, 58, 60], [62, 64, 66, 68, 70], [72, 74, 76, 78, 80], [82, 84, 86, 88, 90], [92, 94, 96, 98, 100]]
4:
    0   1   2   3   4   5   6   7   8    9
0  A   2   3   4   5   6   7   8   9   10
1  A  12  13  14  15  16  17  18  19   20
2  B  22  23  24  25  26  27  28  29   30
3  C  32  33  34  35  36  37  38  39   40
4  D  42  43  44  45  46  47  48  49   50
5  E  52  53  54  55  56  57  58  59   60
6  E  62  63  64  65  66  67  68  69   70
7  E  72  73  74  75  76  77  78  79   80
8  F  82  83  84  85  86  87  88  89   90
9  F  92  93  94  95  96  97  98  99  100
5:
    0   1   2   3   4   5   6   7   8   9
0  A   2   3   4   5   6   7   8   9  10
1  A  12  13  14  15  16  17  18  19  20
2  B  22  23  24  25  26  27  28  29  30
3  C  32  33  34  35  36  37  38  39  40
4  D  42  43  44  45  46  47  48  49  50
6:
 0
A     18
B     24
C     34
D     44
E    192
F    178
Name: 3, dtype: int64

C:\Users\aayush.verma\AppData\Local\Temp\ipykernel_33500\2722169999.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['A', 'A', 'B', 'C', 'D', 'E', 'E', 'E', 'F', 'F']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.iloc[:, 0] = ['A', 'A', 'B', 'C', 'D', 'E', 'E', 'E', 'F', 'F']

In [70]:
print("1:", l1)
print("2:", l2)
print("3:", l3)
print("4:\n", df)
print("5:\n", df_filtered)
print("6:\n", grouped_sum)
print("7:", l7)

1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
2: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40], [41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [51, 52, 53, 54, 55, 56, 57, 58, 59, 60], [61, 62, 63, 64, 65, 66, 67, 68, 69, 70], [71, 72, 73, 74, 75, 76, 77, 78, 79, 80], [81, 82, 83, 84, 85, 86, 87, 88, 89, 90], [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
3: [[2, 4, 6, 8, 10], [12, 14, 16, 18, 20], [22, 24, 26, 28, 30], [32, 34, 36, 38, 40], [42, 44, 46, 48, 50], [52, 54, 56, 58, 60], [62, 64, 66, 68, 70], [72, 74, 76, 78, 80], [82, 84, 86, 88, 90], [92, 94, 96, 98, 100]]
4:
    0   1   2   3   4   5   6   7   8    9
0  A   2   3   4   5   6   7   8   9   10
1  A  12  13  14  15  16  17  18  19   20
2  B  22  23  24  25  26  27  28  29   30
3  C  32  33  34  35  36  37  38  39   40
4  D  42  43  44  45  46  47  48  49   50
5  E  52  53  54  55  56  57  58  59   60
6  E  62  63  64  65  66  67  68  69   70
7  E  72  73  74  75  76  77  78  79   80
8  F  82  83  84  85  86  87  88  89   90
9  F  92  93  94  95  96  97  98  99  100
5:
    0   1   2   3   4   5   6   7   8   9
0  A   2   3   4   5   6   7   8   9  10
1  A  12  13  14  15  16  17  18  19  20
2  B  22  23  24  25  26  27  28  29  30
3  C  32  33  34  35  36  37  38  39  40
4  D  42  43  44  45  46  47  48  49  50
6:
 0
A     18
B     24
C     34
D     44
E    192
F    178
Name: 3, dtype: int64
7: [['A', 'A', 'B', 'C', 'D', 'E', 'E', 'E', 'F', 'F'], [2, 12, 22, 32, 42, 52, 62, 72, 82, 92], [3, 13, 23, 33, 43, 53, 63, 73, 83, 93], [4, 14, 24, 34, 44, 54, 64, 74, 84, 94], [5, 15, 25, 35, 45, 55, 65, 75, 85, 95], [6, 16, 26, 36, 46, 56, 66, 76, 86, 96], [7, 17, 27, 37, 47, 57, 67, 77, 87, 97], [8, 18, 28, 38, 48, 58, 68, 78, 88, 98], [9, 19, 29, 39, 49, 59, 69, 79, 89, 99], [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]]